Use deb repo
SOSETH/docker pull request #3
Opened 2020-01-26 14:43 UTC by niklassc7

2020-01-26 14:46 UTC, niklassc7 commented
I thought docker-compose wasn't in the stretch repos, that's why I at first didn't use apt.

I removed `cache_valid_time: 1800` because it led to an error when the cache was refreshed within the last 30 minutes. In this pull request, however, its back.

2020-01-27 07:27 UTC, uubk requested changes
A few small nitpicks, otherwise this looks good :+1:

2020-01-27 07:27 UTC, uubk commented on defaults/main.yml
> +install_docker_compose: False
Please prefix with `docker_` (e.g. `docker_install_compose`)

2020-01-27 07:27 UTC, uubk commented on defaults/main.yml
> +docker_compose_version: "1.25.0"
This is no longer used, right?

2020-01-27 07:27 UTC, uubk commented on tasks/main.yml
> +  when: install_docker_compose | bool
The `|bool` filter should not be necessary, as the variable is already a boolean.

2020-02-02 20:09 UTC, uubk commented
Rebased and merged manually (which GitHub can't detect), closing PR.

2020-02-02 20:09 UTC, closed without merging